"""004_add counterparty_user_id to rating_ledger

Revision ID: 004
Revises: 6be5a5d97806
Create Date: 2026-02-26 12:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '004'
down_revision: str | Sequence[str] | None = '6be5a5d97806'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'rating_ledger',
        sa.Column(
            'counterparty_user_id',
            sa.BigInteger(),
            nullable=True,
            comment='Вторая сторона операции (для переводов)',
        ),
    )
    op.create_foreign_key(
        'fk_rating_ledger_counterparty_user_id',
        'rating_ledger',
        'users',
        ['counterparty_user_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_index(
        'idx_rating_ledger_counterparty',
        'rating_ledger',
        ['counterparty_user_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rating_ledger_counterparty', table_name='rating_ledger')
    op.drop_constraint(
        'fk_rating_ledger_counterparty_user_id',
        'rating_ledger',
        type_='foreignkey',
    )
    op.drop_column('rating_ledger', 'counterparty_user_id')
    # ### end Alembic commands ###
