"""002_add rating_ledger_table

Revision ID: 413f20173ebb
Revises: 001
Create Date: 2026-01-11 18:23:37.234189

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '413f20173ebb'
down_revision: str | Sequence[str] | None = '001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_ledger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('initiator_user_id', sa.BigInteger(), nullable=True, comment='Кто инициировал операцию (user/system/bot)'),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=True),
    sa.Column('operation_type', sa.String(length=32), nullable=False),
    sa.Column('operation_subtype', sa.String(length=32), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_reverted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reverted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reverted_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['initiator_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reverted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rating_ledger_chat_user', 'rating_ledger', ['chat_id', 'user_id'], unique=False)
    op.create_index('idx_rating_ledger_created_at', 'rating_ledger', ['created_at'], unique=False)
    op.create_index('idx_rating_ledger_source', 'rating_ledger', ['source_type', 'source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rating_ledger_source', table_name='rating_ledger')
    op.drop_index('idx_rating_ledger_created_at', table_name='rating_ledger')
    op.drop_index('idx_rating_ledger_chat_user', table_name='rating_ledger')
    op.drop_table('rating_ledger')
    # ### end Alembic commands ###
