"""Add fields to users table for bot

Revision ID: 4e00fdd8041a
Revises: 413f20173ebb
Create Date: 2026-02-02 17:43:36.615610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e00fdd8041a'
down_revision: Union[str, Sequence[str], None] = '413f20173ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('added_by_user', sa.BigInteger(), server_default='0', nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deactivated_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'added_by_user')
    # ### end Alembic commands ###
